[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PYTHON_VERSION = "3.11.0"
NIXPACKS_PYTHON_VERSION = "3.11.0" 