[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/v1"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PYTHON_VERSION = "3.11.0"
NIXPACKS_PYTHON_VERSION = "3.11.0" 