services:
  # Backend API Service
  - type: web
    name: ai-help-center-api
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: backend
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: ai_assistance
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: CORS_ORIGINS
        value: '["https://ai-help-center.vercel.app"]'
      - key: RATE_LIMIT_REQUESTS
        value: "100"
      - key: RATE_LIMIT_PERIOD
        value: "60"