services:
  # Frontend Web Service
  - type: static
    name: ai-help-center-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://ai-help-center-api.onrender.com
      - key: VITE_AI_MODEL
        value: gpt-3.5-turbo
      - key: NODE_VERSION
        value: 18.17.0

  # Backend API Service
  - type: web
    name: ai-help-center-api
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: ai_assistance
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: CORS_ORIGINS
        value: '["https://ai-help-center-frontend.onrender.com"]'
      - key: RATE_LIMIT_REQUESTS
        value: "100"
      - key: RATE_LIMIT_PERIOD
        value: "60"