apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-help-center
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-help-center
  template:
    metadata:
      labels:
        app: ai-help-center
    spec:
      containers:
      - name: ai-help-center
        image: ai-help-center:latest
        ports:
        - containerPort: 3000
        env:
        - name: VITE_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: url
        - name: VITE_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: anon-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"